waza_gestion_homepage:
    path:     /
    defaults: { _controller: WAZAGestionBundle:Default:index }

waza_comptabilite:
    resource: "@WAZAComptabiliteBundle/Resources/config/routing.yml"
    prefix:   /comptabilite
    
waza_settings:
    resource: "@WAZASettingsBundle/Resources/config/routing.yml"
    prefix:   /settings
    
waza_file:
    resource: "@WAZAFileBundle/Resources/config/routing.yml"
    prefix:   /file
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"