<?php

namespace WAZA\SettingsBundle\Repository;

/**
 * SettingsUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingsUserRepository extends \Doctrine\ORM\EntityRepository
{
}
