<?php

namespace WAZA\ComptabiliteBundle\Repository;

/**
 * adresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class adresseRepository extends \Doctrine\ORM\EntityRepository
{
}
