<?php

namespace WAZA\ComptabiliteBundle\Repository;

/**
 * depenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class depenseRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCritere($pattern){
        $qb = $this->createQueryBuilder('d');
        $qb->Where('d.description LIKE :pattern')
            ->orWhere('d.nom LIKE :pattern')
            ->setParameter('pattern', '%' .$pattern. '%');
        return $qb->getQuery()->getResult();
    }
}
