<?php

namespace WAZA\ComptabiliteBundle\Repository;

/**
 * GainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GainRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCritere($pattern){
        $qb = $this->createQueryBuilder('g');
        $qb->Where('g.description LIKE :pattern')
            ->orWhere('g.nom LIKE :pattern')
            ->setParameter('pattern', '%' .$pattern. '%');
        return $qb->getQuery()->getResult();
    }
}
