<?php

namespace WAZA\ComptabiliteBundle\Repository;

/**
 * mesureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class mesureRepository extends \Doctrine\ORM\EntityRepository
{
}
