<?php

namespace WAZA\ComptabiliteBundle\Repository;

/**
 * monnaieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class monnaieRepository extends \Doctrine\ORM\EntityRepository
{
}
