<?php

namespace WAZA\ComptabiliteBundle\Repository;

/**
 * objetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class objetRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCritere($pattern){
        $qb = $this->createQueryBuilder('o');
        $qb->Where('o.description LIKE :pattern')
            ->orWhere('o.nom LIKE :pattern')
            ->setParameter('pattern', '%' .$pattern. '%');
        return $qb->getQuery()->getResult();
    }
}
