<?php

namespace WAZA\ComptabiliteBundle\Repository;

/**
 * producteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class producteurRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCritere($pattern){
        $qb = $this->createQueryBuilder('p');
        $qb->Where('p.nom LIKE :pattern')
            ->orWhere('p.prenom LIKE :pattern')
            ->orWhere('p.tel LIKE :pattern')
            ->orWhere('p.pays LIKE :pattern')
            ->orWhere('p.codepostal LIKE :pattern')
            ->orWhere('p.ville LIKE :pattern')
            ->orWhere('p.rue LIKE :pattern')
            ->setParameter('pattern', '%' .$pattern. '%');
        return $qb->getQuery()->getResult();
    }
}
