<?php

namespace WAZA\ComptabiliteBundle\Repository;

/**
 * produireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class produireRepository extends \Doctrine\ORM\EntityRepository
{
}
