<?php

namespace WAZA\ComptabiliteBundle\Repository;

/**
 * residerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class residerRepository extends \Doctrine\ORM\EntityRepository
{
}
