<?php

namespace WAZA\FileBundle\Repository;

/**
 * FormatExportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormatExportRepository extends \Doctrine\ORM\EntityRepository
{
}
